title: Habitable Life
author: Timothy Welch
description: Building a life you can live in
baseurl: /habitablelife
basewebsite: /habitablelife
theme: minima
minima:
  skin: solarized
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
# plugins:
#    - jekyll-feed
