site_name: Habitable Life
site_url: https://tim-welch.github.io/blog-material
site_author: Timothy Welch
copyright: Copyright &copy; 2025 Timothy Welch

theme:
  name: material
  custom_dir: overrides
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: fontawesome/solid/book-bible
  # favicon: assets/favicon.ico
  features:
    - navigation.footer
    # - navigation.sections
    - navigation.instant
    - navigation.indexes
    # - navigation.tabs
    - toc.follow
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Light mode

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true

  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.details

extra:
  generator: true
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/timothyewelch
    - icon: fontawesome/solid/blog
      link: https://tim-welch.github.io/habitablelife

# extra_css:
#   - stylesheets/backlinks-admonition.css

plugins:
  - search
  - offline
  - tags
  - meta
  - glightbox:
      skip_classes: 
        - collapse-btn
  - nodegraph:
      graphfile: "nodegraph.html"  
  - backlinks_section:
      title: Linked mentions
      ignore_links_to:
      - index.md
#  - blog:
#      blog_dir: .
#      post_dir: "{blog}/notes"
#      blog_toc: true
#      post_date_format: full
#      post_url_format: "note/{slug}"

  

#nav:
#  - Home: index.md
#  - Maps of Content:
#    - Examples: maps/examples.md
# not_in_nav:
#   /Bible/*
